### ISSUE TITLE
No issue but question about 2020/020_explain_BT2407

### ISSUE THREAD

**Issue by emcodem** [toru-ver4/sample_code#214]
OK, so first of all it is so nice from you to share all your experiments here. I feel like i look at a picture of inside your brain and it is a beautiful (very structured) thing to see! 
Just very quick question, why did you choose Annex 2 of BT.2407? Did you personally find that most appealing or did you have some outside or company requirement to look at it?

My interest is because i was working on BT.2111 colorbar the last weeks and it took me like 2 weeks to understand everything and be able to apply  § 2 of Report ITU-R BT.2407 – “Simple conversion from BT.2020 to BT.709 based on linear matrix transformation”. (after all i had 100% matching values :D)

**Comment by toru-ver4** [comment]
Hi, I'll be glad to answer your question.

The reasons why I choose BT.2407 Annex 2 are as follows.

* BT.2407 Annex 2 was developed by Japanese broadcaster NHK
* I was interested in NHK's method because I'm Japanese
* In addition, although BT.2407 Annex 2 has complex algorithms, I felt it was implementable because there were many figures and equations


As an aside, I had the opportunity to meet the inventor of BT.2407 Annex 2 last year.
He is also the inventor of Gamut Rings, and we had an exciting discussion about color science😊

**Comment by emcodem** [comment]
That makes a lot of sense, thank you for taking the time to explain it. I should be able to try your method and verify the roundtrip capabilities in the next time. BT.2087 mentions that Annex2 is not "reversible" but roundtrip compatible with BT.2087 "upmapping", this and visual quality is what caught my interest. 

Might i ask a follow up question: have you ever been able to verify the outcome of this research with the inventors? I read they made a 128 size lut for it but it does not seem to be public. So i guess to test Annex2, the easiest existing method is to compile them using your magnificent source code :D

**Comment by toru-ver4** [comment]
Unfortunately, I never conducted the verification process with the inventor.
Instead, I validated the algorithm using my own test patterns.
Below is a comparison between the 3x3 matrix method and gamut mapping.
http://drive.google.com/uc?export=view&id=1NMFysmlQ5KN7eTjRfjRo44WZAqmWNQoj

I also performed the following validation tests.
https://www.youtube.com/watch?v=_I8uw19BiuM

Also, I neglected to mention earlier, but I have stored my implementation results as 3DLUTs with sizes of 33x33x33, 65x65x65, and 129x129x129. Feel free to use them if you wish.
https://drive.google.com/file/d/16Pl8p79fFIk08bFJ0c1DEx5wkDS4rKcq/view
(They have been published on [my blog](https://trev16.hatenablog.com/entry/2020/06/07/094646))

**Comment by emcodem** [comment]
Thank you very much for the links and your very interesting blog, i love your work!
Using your LUT, i possibly discovered an error in BT.2407 (https://www.itu.int/dms_pub/itu-r/opb/rep/R-REP-BT.2407-2017-PDF-E.pdf): 
In Page 5, Table1, they state that Annex2 method should be "roundtrip compatible with BT 2087 upconversion". But as Annex2 method maps about 100% HLG into 709, i think it is impossible that BT.2087 upconversion can be used for roundtrip. This is because 2087 maps 100% 709 to 75% HLG. So there is no way we can go HLG-709-HLG-709 using these 2 methods. 

Might i ask if you have ever heared about or can imagine that the Annex2 method can be reversed? Of course this is far out of scope of your investigations here but i thought you might have some opinion and interest in it too...

**Comment by toru-ver4** [comment]
> Might i ask if you have ever heard about or can imagine that the Annex2 method can be reversed?

The BT.2407 Annex 2 method is non-invertible. The data after BT.2020 to BT.709 conversion lacks the information needed for a BT.709 to BT.2020 reverse conversion.

However, BT.2407 Annex 2 has a unique characteristic: data within the BT.709 gamut remains unchanged.
(Here is a verification demo I used: https://www.youtube.com/watch?v=OOBO875dGTg)

Thus, if you perform the following steps, the data within the BT.709 gamut will remain unchanged:

Step 1: Convert from BT.2020 to BT.709 using BT.2407 Annex 2.
Step 2: Convert from BT.709 to BT.2020 using BT.2087. (After this conversion, there is no color data outside of BT.709.)
Step 3: Convert from BT.2020 to BT.709 using BT.2407 Annex 2. (The result of this conversion matches the result from Step 1, because the data within the BT.709 gamut remains unchanged.)

I believe the feature indicating 'Yes' for 'Roundtrip Possible with BT.2087' is due to this characteristic.

While you mentioned HLG, I highly recommend considering gamut mapping and tone mapping separately when evaluating roundtrip performance. The performance of gamut mapping should be assessed in the **SDR space**, and introducing HDR space can complicate things considerably. In fact, in BT.2446, HDR to SDR conversion (tone mapping) is performed first to enable BT.2020 to BT.709 conversion (gamut mapping) in the SDR space.

I hope this information is useful in your research.
